$(".header").click(function(){
    $(".header").css("background-color","red");
})
$(".sidebar").click(function(){
    $("span").html("Leftbar");
})
$(".extraContent").click(function(){
    $(".mainContent").fadeOut();
})